### ISSUE TITLE
Does this work with @vue/compat?

### ISSUE THREAD

**Issue by NikhilVerma** [underfin/vite-plugin-vue2#127]
According to the Vue upgrade workflow it's possible to make it work with Vue2. However when I [follow the steps](https://v3.vuejs.org/guide/migration/migration-build.html#installation) (especially removing the template compiler and replacing it with `@vue/compiler-sfc`). I get the following error

```
failed to load config from /code/vite.config.js
error when starting dev server:
Error: Cannot find module 'vue-template-compiler'
Require stack:
- /code/node_modules/vite-plugin-vue2/dist/utils/descriptorCache.js
- /code/node_modules/vite-plugin-vue2/dist/main.js
- /code/node_modules/vite-plugin-vue2/dist/index.js
- /code/vite.config.js
- /code/node_modules/vite/dist/node/chunks/dep-98dbe93b.js
- /code/node_modules/vite/dist/node/cli.js
- /code/node_modules/vite/bin/vite.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/code/node_modules/vite-plugin-vue2/dist/utils/descriptorCache.js:30:42)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .js] (/code/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:76008:13)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/code/node_modules/vite-plugin-vue2/dist/main.js:10:27)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .js] (/code/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:76008:13)
```

**Comment by antfu** [comment]
For `@vue/compat` I believe you should use `@vitejs/plugin-vue` instead.
