### ISSUE TITLE
.less has no corresponding SFC entry in the cache. This is a vite-plugin-vue2 internal error

### ISSUE THREAD

**Issue by Rainmen-xia** [underfin/vite-plugin-vue2#136]
/test/scenarioInfo/scenarioInfo.less has no corresponding SFC entry in the cache. This is a vite-plugin-vue2 internal error, please open an issue.
      at Object.getDescriptor (/myroot/git/uat/projectName/node_modules/vite-plugin-vue2/src/utils/descriptorCache.ts:46:11)
      at Context.load (/myroot/git/uat/projectName/node_modules/vite-plugin-vue2/src/index.ts:114:28)
      at Object.load (/myroot/github/vite/packages/vite/src/node/server/pluginContainer.ts:489:42)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at transformRequest (/myroot/github/vite/packages/vite/src/node/server/transformRequest.ts:70:22)
      at viteTransformMiddleware (/myroot/github/vite/packages/vite/src/node/server/middlewares/transform.ts:170:24)

**Comment by Rainmen-xia** [comment]
这个less文件被另外一个vue
文件引入：
`
![image](https://user-images.githubusercontent.com/5163662/134377677-aed44541-8372-4f72-ba78-1e02fe4ee2c0.png)
`

**Comment by Rainmen-xia** [comment]
可能是在vue文件中引入了一个less文件。在less文件中引入了.svg文件

**Comment by Rainmen-xia** [comment]
here, you can repreduction: https://github.com/Rainmen-xia/vite-vue2-demo

**Comment by Rainmen-xia** [comment]
看样子是.less文件里面的图片路径处理错误

**Comment by Rainmen-xia** [comment]
test.vue
`
...
<style scoped src='test.less'></style>
`

test.less
`
.icon{
  display: inline-block;
  width: 18px;
  height: 18px;
  background: url("./icon-right.svg") no-repeat  center center;
  vertical-align: middle;
  margin-left: 8px;
}
`
url("./icon-right.svg")这个路径会被转成：

url("/less/less.less?vue&type=style&index=0&from=/rootPath/vite-plugin-vue2/playground/less/icon-right.svg\")
