### ISSUE TITLE
Relative path error

### ISSUE THREAD

**Issue by 949054042** [underfin/vite-plugin-vue2#150]
when i try to import a component relatively, i got a error like this
![image](https://user-images.githubusercontent.com/29389190/141084729-7b1a4271-a11c-4ed7-a3e6-49cc96b9f450.png)

**Comment by kskalski** [comment]
With version 1.8.2 (also 1.9.0) I got this kind of regression too:

```
[vite-plugin-vue2] D:\rep\path\component.vue has no corresponding SFC entry in the cache. This is a vite-plugin-vue2 internal error, please open an issue.
file: D:/rep/path/component.scss?vue&type=style&index=0&from=D:\rep\path\component.vue&src&lang.scss
error during build:
Error: D:\rep\path\component.vue has no corresponding SFC entry in the cache. This is a vite-plugin-vue2 internal error, please open an issue.
    at getDescriptor (D:\rep\path1\WebCommonUI\node_modules\vite-plugin-vue2\dist\utils\descriptorCache.js:63:15)
    at Object.transform (D:\rep\path1\WebCommonUI\node_modules\vite-plugin-vue2\dist\index.js:108:68)
    at D:\rep\path1\WebCommonUI\node_modules\vite\node_modules\rollup\dist\shared\rollup.js:22620:25
```

works fine when downgrading to 1.8.1
