### ISSUE TITLE
Support for vue-class-component

### ISSUE THREAD

**Issue by Djaler** [underfin/vite-plugin-vue2#28]
Source:
```
<template>
    <div>
        {{ text }}
    </div>
</template>

<script lang="ts">
    import { Component, Vue } from 'vue-property-decorator';

    @Component
    export default class App extends Vue {
        text = 'text';
    }
</script>
```

Result:
```
[plugin:vite-plugin-vue2] Transform failed with 1 error:
D:/Projects/js-playground/src/App.vue:11:0: error: Expected "class" but found "const"
D:/Projects/js-playground/src/App.vue:11:0
Expected "class" but found "const"
8  |  import { Component, Vue } from 'vue-property-decorator';
9  |  
10 |  @Component
   |             ^
11 |  const script = class App extends Vue {
   |  ^
12 |      text = 'text';
    at failureErrorWithLog (D:\Projects\js-playground\node_modules\.pnpm\esbuild@0.8.36\node_modules\esbuild\lib\main.js:969:15)
    at D:\Projects\js-playground\node_modules\.pnpm\esbuild@0.8.36\node_modules\esbuild\lib\main.js:852:33
    at handleIncomingPacket (D:\Projects\js-playground\node_modules\.pnpm\esbuild@0.8.36\node_modules\esbuild\lib\main.js:566:9)
    at Socket.readFromStdout (D:\Projects\js-playground\node_modules\.pnpm\esbuild@0.8.36\node_modules\esbuild\lib\main.js:482:7)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23
```

**Comment by Djaler** [comment]
Can you look at this? https://github.com/vitejs/vite/commit/d3397e61cd9d0761606506dcc176a1cbc845d8b5

**Comment by Djaler** [comment]
Can you please release a new version with this fix?

**Comment by underfin** [comment]
Please use v1.2.0

**Comment by Djaler** [comment]
Thanks!

**Comment by zqcccc** [comment]
Is that possible to use a decorator like the below codes ?
```vue
<script lang="jsx">
import Vue from 'vue'
import VueClassDecorator from 'vue-class-component'

@VueClassDecorator({})
export default class ProjectIndex extends Vue {}
</script>
```
