### ISSUE TITLE
vite.ssrLoadModule fails with plugin.

### ISSUE THREAD

**Issue by blake-newman** [underfin/vite-plugin-vue2#31]
I believe the fix to #24 causes separate issue with `vite.ssrLoadModule`

`Error: failed to load module for ssr: /@id/__x00__/vite/vueComponentNormalizer` this may be a problem with Vite - however undoing this change fixes this issue.

For context `vite.ssrLoadModule` is used in instances of creating a [SSR dev server middleware.](https://github.com/vitejs/vite/tree/main/packages/playground/ssr)

**Comment by blake-newman** [comment]
This is a seperate issue but while i'm here there is another issue when using this method when using this plugin. 

```
11:47:55 [vite] Error when evaluating SSR module /src/entry/App.vue:
TypeError: Cannot read property 'accept' of undefined
    at null:33:20
    at ssrLoadModule (/home/blake/work/vite-test/node_modules/vite/dist/node/chunks/dep-fed852ba.js:67137:166)
```

This looks to be because `import.meta.hot` is not set on ssr so the hot module update code breaks. I don't have enough familiarity if this should be the case however the code can be fixed as of today by checking that the `import.meta.hot` is available.

https://github.com/underfin/vite-plugin-vue2/blob/master/src/main.ts#L221 can include the check to ensure that HMR is available; to ensure the code does not execute if HMR is not correctly setup.

**Comment by underfin** [comment]
The ssr is not supported for vue2. I will take a look for this.

**Comment by CyberAP** [comment]
Vue 2 SSR is tightly coupled with webpack bundling, so in order for this to work it has to be extracted to behave the same way as `renderToString` in Vue 3. I've tried to do this but failed hard since Vue 2 renderer is far more complex than Vue 3.

**Comment by lzxb** [comment]
I have this problem, too

**Comment by lzxb** [comment]
![image](https://user-images.githubusercontent.com/8424643/114554032-de17dd00-9c98-11eb-96b7-afe44e3b578a.png)
![image](https://user-images.githubusercontent.com/8424643/114554061-e5d78180-9c98-11eb-9b2d-3a26d6e967fa.png)

Remove the hot update and you can use it

**Comment by lzxb** [comment]
```javascript
const express = require('express')
const { createServer: createViteServer, build } = require('vite')
const { createRenderer } = require('vue-server-renderer');
const { createVuePlugin } = require('vite-plugin-vue2')

build({
  plugins: [
      createVuePlugin()
  ]
})

async function createServer() {
  const app = express()

  // 以中间件模式创建 vite 应用，这将禁用 Vite 自身的 HTML 服务逻辑
  // 并让上级服务器接管控制
  const vite = await createViteServer({
    server: { middlewareMode: true },
    plugins: [
        createVuePlugin()
    ]
  });

  // 使用 vite 的 Connect 实例作为中间件
  app.use(vite.middlewares)

  app.use('*', async (req, res) => {
      const renderer = createRenderer();
      try {
          const { default: createApp } = await vite.ssrLoadModule('src/entry-server.js');
          const html = await renderer.renderToString(createApp());
          res.send(html);
      } catch(e) {
        vite.ssrFixStacktrace(e)
        console.error(e)
        res.status(500).end(e.message)
      }
  })

  app.listen(3000)
}

createServer()
```

**Comment by lzxb** [comment]
```json
{
  "name": "c-demo",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "express": "^4.17.1",
    "vite": "^2.1.5",
    "vite-plugin-vue2": "^1.4.3",
    "vue": "^2.6.12",
    "vue-server-renderer": "^2.6.12"
  }
}

```

**Comment by mborejdo** [comment]
Is there anything preventing the "workarounds" to land? I am also running into this problem, but can solve it with the mentioned patches.

**Comment by frsdun** [comment]
Just wondering if there is any progress on this?
I am also getting the error:

`Error: failed to load module for ssr: __x00__/vite/vueComponentNormalizer
    at instantiateModule (/home/duncan/Projects/vue2_vite/node_modules/vite/src/node/ssr/ssrModuleLoader.ts:71:11)`

Trying to use vite-plugin-vue2 with vite-plugin-ssr

**Comment by euoia** [comment]
@mborejdo Would you mind elaborating on how you fixed it? I am also trying to get SSR working (ideally with static site generation) using Vue 2 + Vite.

**Comment by mborejdo** [comment]
basically whats written here: https://github.com/underfin/vite-plugin-vue2/issues/31#issuecomment-818705705
We did not use this solution tho due to other problems (eg. scoped styling issues, etc)

**Comment by zhangyuang** [comment]
@underfin Is there any progress?

**Comment by LikeDege** [comment]
@underfin Is there any progress?
