### ISSUE TITLE
This localhost page can’t be found.

### ISSUE THREAD

**Issue by adepranaya** [underfin/vite-plugin-vue2#57]
Hi Underfin when I install this plugin and run with `yarn dev` 

the page is not found
`This localhost page can’t be found. No webpage was found for the web address: http://localhost:3000/
HTTP ERROR 404`

this is my `package.json`

```json
{
  "name": "myvue2-project",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "dev": "vite"
  },
  "dependencies": {
    "axios": "^0.20.0",
    "chart.js": "^2.9.3",
    "core-js": "^2.6.5",
    "nprogress": "^0.2.0",
    "vue": "^2.6.12",
    "vue-chartjs": "^3.5.1",
    "vue-cropperjs": "^4.2.0",
    "vue-router": "^3.0.3",
    "vue-toasted": "^1.1.28",
    "vuetify": "^2.2.11",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@fortawesome/fontawesome-free": "^5.15.1",
    "@vitejs/plugin-vue": "^1.1.5",
    "@vue/cli-plugin-babel": "^3.12.0",
    "@vue/cli-plugin-eslint": "^3.12.0",
    "@vue/cli-service": "^3.12.0",
    "@vue/eslint-config-prettier": "^5.0.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.16.0",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-vue": "^5.0.0",
    "prettier": "^1.18.2",
    "sass": "^1.19.0",
    "sass-loader": "^8.0.0",
    "vite": "^2.1.2",
    "vite-plugin-vue2": "^1.4.2",
    "vue-cli-plugin-vuetify": "^2.0.7",
    "vue-template-compiler": "^2.6.10",
    "vuetify-loader": "^1.3.0"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "@vue/prettier"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ],
  "peerDependencies": {}
}
```

can u help me?

**Comment by underfin** [comment]
I hasn't idea for this, can you give a reproduction for this?

**Comment by adepranaya** [comment]
this is my slim copy private project https://github.com/adepranaya/cp-fe-vite about my question

**Comment by userquin** [comment]
@adepranaya  since you are using vite running `dev` script, you need to move/copy index.html and main.js to root folder. The vite template by default expects this 2 files to be on root folder: you can change with vite config.

What a difference running serve and dev: my laptop is a 9900K with 64GB of memory and SSD NVME Samsung PRO 970, with webpack 58525ms and with vite only 10 seconds 

I just try to build vite version adding this script to `package.json`: 
```json
"vite-build": "vite build"
```

the out will be something like this:
```shell
Could not resolve entry module (index.html).
error during build:
Error: Could not resolve entry module (index.html).
    at error (F:\work\projects\quini\vite-plugin-vue2-examples\cp-fe-vite\node_modules\rollup\dist\shared\rollup.js:5300:30)
    at ModuleLoader.loadEntryModule (F:\work\projects\quini\vite-plugin-vue2-examples\cp-fe-vite\node_modules\rollup\dist\shared\rollup.js:18515:20)
    at async Promise.all (index 0)
 ERROR  Command failed with exit code 1.
```

Then copying `public/index.html` and `src/main.js` to `/` and adding this line bellow `<div id="app"></div>`:
```html
<script type="module" src="/src/main.js"></script>
```

I now can build the project with vite: I have changed all you `@`  with `/src`, adding the extensions for all types: for exmaple, for `js` files adding the extension, for importing components just adding all `.vue` extensions.

```shell
vite v2.1.3 building for production...
transforming (24) node_modules\vuetify\lib\index.js[plugin:rollup-plugin-dynamic-import-variables] invalid import "import(`/src/layouts/${this.name}.vue`)". Variable absolute imports are not supported, imports
must start with ./ in the static part of the import. For example: import(`./foo/${bar}.js`).
✓ 544 modules transformed.
dist/assets/fa-brands-400.407a9723.eot      131.20kb
dist/assets/fa-regular-400.cf83ffb8.eot     33.24kb
dist/assets/fa-solid-900.75a76115.eot       198.27kb
dist/assets/fa-brands-400.43c072c1.woff2    74.96kb
dist/assets/fa-regular-400.8afc6e5e.woff2   12.96kb
dist/assets/fa-solid-900.d0b4256a.woff2     76.36kb
dist/assets/fa-regular-400.14c9db4f.woff    15.89kb
dist/assets/fa-brands-400.aff76e5c.woff     87.95kb
dist/assets/fa-solid-900.74edc18b.woff      99.27kb
dist/assets/fa-regular-400.c651b8a6.ttf     32.95kb
dist/assets/fa-brands-400.06f4d009.ttf      130.90kb
dist/assets/fa-solid-900.3d06af1f.ttf       197.99kb
dist/assets/fa-regular-400.2326849b.svg     141.32kb
dist/assets/fa-brands-400.679b5a52.svg      730.02kb
dist/assets/fa-solid-900.fa498fb2.svg       897.45kb
dist/index.html                             1.43kb
dist/assets/vendor.547aa650.css             593.82kb / brotli: skipped (large chunk)
dist/assets/Layout.d8388705.js              0.44kb / brotli: 0.23kb
dist/assets/Dashboard.a7b4a109.js           0.92kb / brotli: 0.49kb
dist/assets/404.087fe3f6.js                 0.88kb / brotli: 0.46kb
dist/assets/403.4c0b8dd6.js                 0.89kb / brotli: 0.48kb
dist/assets/index.5c3eed66.js               16.91kb / brotli: 5.15kb
dist/assets/index.7166ec58.css              57.65kb / brotli: 10.25kb
dist/assets/vendor.317e131a.js              188.86kb / brotli: 56.90kb
```

The `dev` script is now running, I only need to change on `src/axios/index.js` the usage of `process.env`, we need to use `import.meta.env` instead and change `VUE_` prefix with `VITE_` prefix. The page at least is showing, I think not working due to axios problem:

![imagen](https://user-images.githubusercontent.com/6311119/112721826-55faaf00-8f06-11eb-8102-0c2bd19fb089.png)

If you need a path just request me, I'll upload here if you want.

**Comment by userquin** [comment]
@underfin if I use this on `src/layouts/Layout.js`:
```javascript
    if (!Vue.options.components[this.name]) {
      Vue.component(this.name, () => import(`/src/layouts/${this.name}.vue`));
    }
```
on build, vite warns with:
```shell
transforming (24) node_modules\vuetify\lib\index.js[plugin:rollup-plugin-dynamic-import-variables] invalid import "import(`/src/layouts/${this.name}.vue`)". Variable absolute imports are not supported, imports
must start with ./ in the static part of the import. For example: import(`./foo/${bar}.js`).
```

but if I change it to be relative, then it is not imported... blank page, any ideas?

**Comment by userquin** [comment]
@adepranaya seems to be a problem with the layout, the original looks like this:

![imagen](https://user-images.githubusercontent.com/6311119/112722286-ecc86b00-8f08-11eb-8d8d-0a0ef376a80c.png)

**Comment by userquin** [comment]
@adepranaya I have it working, just some changes to `vuetify` plugin (registering components used on app, seems we need to use for example `rollup-plugin-vuetify` to resolve components) and `vite` conf:

@underfin the problem is not in the layout: the problem was vueitfy components not imported, I do a manual configuration.

`src/plugins/vuetify.js`
```javascript
import "@fortawesome/fontawesome-free/css/all.css"; // Ensure you are using css-loader
import Vue from "vue";
import Vuetify, {
  VApp,
  VCard,
  VMain,
  VIcon,
  VContainer,
  VBreadcrumbs,
  VRow,
  VCol,
  VBtn
} from "vuetify/lib";

Vue.use(Vuetify, {
  components: {
    VApp,
    VCard,
    VMain,
    VIcon,
    VContainer,
    VBreadcrumbs,
    VRow,
    VCol,
    VBtn
  }
});

export default new Vuetify({});
```
`vite.config.js`
```javascript
// vite.config.js
const { createVuePlugin } = require("vite-plugin-vue2");

module.exports = {
  assetsInclude: "src/assets/*",
  plugins: [createVuePlugin(/*options*/)]
};
```
![imagen](https://user-images.githubusercontent.com/6311119/112723893-01a8fc80-8f11-11eb-8069-98e3681557b3.png)

**Comment by userquin** [comment]
Copying `index.html` and adding the module to it, and changing only vite configuration, vuetify plugin and axios it is working:
- copy `/public/index.html` to root folder: add `<script type="module" src="/src/main.js"></script>` below `<div id="app"></div>`.
- modify `vite.config.js` with this:
```javascript
// vite.config.js
import path from "path";
const { createVuePlugin } = require("vite-plugin-vue2");

module.exports = {
  assetsInclude: "src/assets/*",
  resolve: {
    alias: {
      "@": `${path.resolve(__dirname, "src")}`
    }
  },

  plugins: [createVuePlugin(/*options*/)]
};
```
- modify `src/plugin/vuetify.js` with this:
```javascript
import "@fortawesome/fontawesome-free/css/all.css"; // Ensure you are using css-loader
import Vue from "vue";
import Vuetify, {
  VApp,
  VCard,
  VMain,
  VIcon,
  VContainer,
  VBreadcrumbs,
  VRow,
  VCol,
  VBtn
} from "vuetify/lib";

Vue.use(Vuetify, {
  components: {
    VApp,
    VCard,
    VMain,
    VIcon,
    VContainer,
    VBreadcrumbs,
    VRow,
    VCol,
    VBtn
  }
});

export default new Vuetify({});
```
- modify `src/axios/index.js` `baseURL` entry with: `baseURL: import.meta.env.VITE_APP_API_BASE_URL`

**Comment by adepranaya** [comment]
@userquin wow your explanation is very good, I have tried it and it works.
now I'm trying it on my private project. I hope the results are the same as what you have described. Thank you very much
